name: a3050s
description: A media player to preview itunes.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  #--------------------MAIN
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  flutter_native_splash:
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  hydrated_bloc:
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  path_provider: ^2.0.12
  rxdart: ^0.27.7
  universal_platform: ^1.0.0+1
  url_strategy: ^0.2.0

  #----------------------I18N
  # flutter_localizations:
  #   sdk: flutter
  # intl: ^0.17.0
  # slang: ^3.11.1

  #--------------------DEBUGGING
  logger: ^1.1.0

  #--------------------THEME

  #--------------------WIDGETS
  fluttertoast: ^8.1.1
  just_audio: ^0.9.31

  #--------------------NETWORK
  cached_network_image:
  http:

  #--------------------NAVIGATIONS
  auto_route: ^5.0.4

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  injectable_generator: ^2.1.3
  slang_flutter: ^3.11.0
  slang_build_runner: ^3.11.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
